services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.permissionService:
        class: AdminBundle\Services\PermissionService
        arguments: ["@common.array", "@service_container"]
    
    app.token_authenticator:
        class: AdminBundle\Security\TokenAuthenticator
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "@service_container"]

    # app.webservice_admin_provider:
    #     class: AdminBundle\Security\Admin\WebserviceAdminProvider

    # app.webservice_admin_provider:
    #     class: AdminBundle\Security\Admin\WebserviceAdminProvider
        #calls: #set注入
        #    - [setMailer, ['@app.mailer']]

