services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.permissionService:
        class: AdminBundle\Services\PermissionService
        #arguments: ["@service_id", "plain_value", "%parameter%"]
