services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.permissionService:
        class: AdminBundle\Services\PermissionService
        arguments: ["@utils.array", "@service_container"]
    kernel.request_listener:
        class: AdminBundle\EventListener\RequestListener
        tags: 
            - { name: kernel.event_listener, event: kernel.request }
       
        #calls: #set注入
        #    - [setMailer, ['@app.mailer']]

