services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.permissionService:
        class: AdminBundle\Services\PermissionService
        arguments: ["@common.array", "@service_container"]
    
    app.token_authenticator:
        class: AdminBundle\Security\TokenAuthenticator
        arguments: [""]
        #calls: #set注入
        #    - [setMailer, ['@app.mailer']]

