# doctrine:
#     dbal:
#         default_connection: default
#         connections:
#             default:
#                 driver:   "%database_driver%"
#                 host:     "%database_host%"
#                 port:     "%database_port%"
#                 dbname:   "%database_name%"
#                 user:     "%database_user1%"
#                 password: "%database_password1%"
#                 charset:  UTF8
#             customer:
#                 driver:   "%database_driver%"
#                 host:     "%database_host%"
#                 port:     "%database_port%"
#                 dbname:   "%database_name%"
#                 user:     "%database_user2%"
#                 password: "%database_password2%"
#                 charset:  UTF8

#     orm:
#         default_entity_manager: default
#         entity_managers:
#             default:
#                 connection: default
#                 # mappings:
#                 #     AppBundle:  ~
#                 #     AcmeStoreBundle: ~
#             customer:
#                 connection: customer
#                 # mappings:
#                 #     AcmeCustomerBundle: ~


# Doctrine Configuration
# doctrine:
#     dbal:
#         driver: pdo_mysql
#         host: '%database_host%'
#         port: '%database_port%'
#         dbname: '%database_name%'
#         user: '%database_user%'
#         password: '%database_password%'
#         charset: UTF8
#         # if using pdo_sqlite as your database driver:
#         #   1. add the path in parameters.yml
#         #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
#         #   2. Uncomment database_path in parameters.yml.dist
#         #   3. Uncomment next line:
#         #path: '%database_path%'

#     orm:
#         auto_generate_proxy_classes: '%kernel.debug%'
#         naming_strategy: doctrine.orm.naming_strategy.underscore
#         auto_mapping: true