# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    #加密方式
    encoders:
        
        AdminBundle\Entity\Admin: 
            algorithm: md5
            #cost: 12

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # in_memory:
        #     memory: ~
        our_db_provider:
            entity:
                class: AdminBundle:Admin
                property: username
        # webservice:
        #     id: app.webservice_admin_provider
    

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: /admin/passport/login
                check_path: /admin/passport/login
                default_target_path: /admin/system/users
                username_parameter: _username
                password_parameter: _password
            # activate different ways to authenticate
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            logout:
                path: /logout
                target: /admin/passport/login
            
            guard:
                authenticators:
                    - app.token_authenticator

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
    access_control: 
        - { path: ^/admin/passport/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }