# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    AppBundle.db.table_prefix: jc_

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    
    # kernel.example_listener:
    #     class: AppBundle\EventListener\ExampleListener
    #     tags: 
    #          - { name: kernel.event_listener, event: kernel.request }
    # kernel.filter_order_event:
    #     class: AppBundle\EventListener\FilterOrderEvent
    #     tags: 
    #          - { name: kernel.event_listener, event: store.order }