<?php

namespace AdminBundle\Repository;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminPositionRepository extends \Doctrine\ORM\EntityRepository
{
}
