<?php

namespace AdminBundle\Repository;

/**
 * BorrowInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowInfoRepository extends \Doctrine\ORM\EntityRepository
{

	public function getList($status = '0')
	{
		$query = $this->getEntityManager()->createQueryBuilder()
		->select('b.id, b.package')
		->from($this->getEntityName(), 'b')
		->where('b.borrowStatus = :borrowStatus')
		->setParameter('borrowStatus', $status)
		->getQuery();
		return $query->getArrayResult();
	}
}
