<?php

namespace AdminBundle\Repository;

/**
 * BorrowInvestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowInvestRepository extends \Doctrine\ORM\EntityRepository
{
}
