# parameters:
#     utils.file.system:  Symfony\Component\Filesystem\Filesystem
#     utils.file.system.IOException: Symfony\Component\Filesystem\Exception\IOException

services:
#    utils.example:
#        class: UtilsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    utils.array:
        class: UtilsBundle\Services\ArrayService
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    # utils.file:
    #     class: UtilsBundle\Services\FileService
    #     arguments: ["%utils.file.system%", "%utils.file.system.IOException%"]
    #     calls: 
    #         - [setFileSystem, ['@app.mailer']]